/* 
 * EONOperator.h
 *
 * This file is generated by SciVi.
 */

#include "EONOpInstance.h"
#include <stdio.h>


namespace EON
{
    static void distance(OpInstance &opInst) // mother = 3
    {
        opInst.output(0) = 42;
        printf(">>> call distance\n");
    }

    static void webSocket(OpInstance &opInst) // mother = 216
    {
        int i = opInst.input(0);
        printf(">>> call webSocket %d, address = %d\n", i, (int)opInst.setting(0));
    }

    static void (*m_operators[])(OpInstance &) = 
    {
        &distance,
        &webSocket
    };

    static MotherNodeID m_operatorsTableLen = 2;

    static MotherNodeID m_operatorsTable[] =
    {
        3,
        216
    };
};
