/* 
 * EONOperator.h
 *
 * This file is generated by SciVi.
 */

#include "EONOpInstance.h"
#include <stdio.h>


namespace EON
{
    static void foo(OpInstance &opInst)
    {
        opInst.output(0) = 42;
        printf(">>> call foo\n");
    }

    static void bar(OpInstance &opInst)
    {
        int i = opInst.input(0);
        printf(">>> call bar %d\n", i);
    }

    static void (*m_operators[])(OpInstance &) = 
    {
        &foo,
        &bar
    };

    static MotherNodeID m_operatorsTableLen = 2;

    static MotherNodeID m_operatorsTable[] =
    {
        20,
        26
    };
};
