/* 
 * EONOperator.h
 *
 * This file is generated by SciVi.
 */

#ifndef __EONOPERATOR_H__
#define __EONOPERATOR_H__

#include <WebSocketsServer.h>
#include "EONOpInstance.h"

extern WebSocketsServer g_webSocket;


namespace EON
{
    static void distance(OpInstance &opInst) // mother UID = 2
    {
        opInst.output(0) = analogRead(0);
        delay(3);
    }

    static void webSocket(OpInstance &opInst) // mother UID = 1
    {
        String msg = String("{") + String((int)opInst.setting(0)) + ":" + String((float)opInst.input(0)) + String("}");
        g_webSocket.broadcastTXT(msg);
    }

    static void (*m_operators[])(OpInstance &) = 
    {
        &distance,
        &webSocket
    };

    static MotherNodeID m_operatorsTableLen = 2;

    static MotherNodeID m_operatorsTable[] =
    {
        2,
        1
    };
};

#endif // __EONOPERATOR_H__
