/* 
 * EONOperator.h
 *
 * This file is generated by SciVi.
 */

#ifndef __EONOPERATOR_H__
#define __EONOPERATOR_H__

#include <WebSocketsServer.h>
#include "EONOpInstance.h"

extern WebSocketsServer g_webSocket;


namespace EON
{
    static void distance(OpInstance &opInst) // mother UID = 2
    {
        const int trigPin = 2; // D4
        const int echoPin = 0; // D3
        pinMode(g_trigPin, OUTPUT);
        pinMode(g_echoPin, INPUT);
        digitalWrite(g_trigPin, LOW);
        delayMicroseconds(2);
        digitalWrite(g_trigPin, HIGH);
        delayMicroseconds(10);
        digitalWrite(g_trigPin, LOW);
        long duration = pulseIn(g_echoPin, HIGH);
        opInst.output(0) = (float)duration * 0.34f / 2.0f;
    }

    static void webSocket(OpInstance &opInst) // mother UID = 1
    {
        String msg = String("[{\"") + String((int)opInst.setting(0)) + "\":" + String((float)opInst.input(0)) + String("}]");
        g_webSocket.broadcastTXT(msg);
    }

    static void adc(OpInstance &opInst) // mother UID = 3
    {
        opInst.output(0) = analogRead(0);
        delay(3);
    }

    static void (*m_operators[])(OpInstance &) = 
    {
        &distance,
        &webSocket,
        &adc
    };

    static MotherNodeID m_operatorsTableLen = 2;

    static MotherNodeID m_operatorsTable[] =
    {
        2,
        1,
        3
    };
};

#endif // __EONOPERATOR_H__
