
//
// This file is automatically generated by SciVi::ES v0.1
//

#ifndef __EONFUNC_H__
#define __EONFUNC_H__

#include "EONValue.h"
#include "EONContainers.h"
#include "MPU6050.h"
#include "Madgwick.h"


namespace EON
{
    class Func
    {
    private:
        bool m_wifiOn;
        bool m_mpuOn;
        MPU6050 m_mpu;
        Madgwick m_madjwick;

        int mapPin(int pin) const;
        void initWS();
        void initMPU();

    public:
        void setup();
        void begin();
        void end();

        Value call(uint8_t opCode, Stack &stack, Heap &heap, Blob &bolb);
    };
};

#endif // __EONFUNC_H__
