/* 
 * EONFunc.h
 *
 * This file is part of SciVi (https://github.com/scivi-tools).
 * Copyright (c) 2019 Konstantin Ryabinin.
 * 
 * This program is free software: you can redistribute it and/or modify  
 * it under the terms of the GNU General Public License as published by  
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but 
 * WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef __EONFUNC_H__
#define __EONFUNC_H__

#include "EONValue.h"
#include "EONContainers.h"


namespace EON
{
    /**
     * The Func class provides methods to control hardware.
     * The content of this class is generated by SciVi according to the users needs.
     */
    class Func
    {
    public:
        void setup();
        void begin();
        void end();

        Value call(uint8_t opCode, Stack &stack);
    };
};

#endif // __EONFUNC_H__
