
//
// This file is automatically generated by SciVi::ES v0.1
//

#ifndef __EONFUNC_H__
#define __EONFUNC_H__

#include "EONValue.h"
#include "EONContainers.h"


namespace EON
{
    class Func
    {
    private:
        bool m_wifiOn;
        int m_meanderTime;
        bool m_meanderState;
        int mapPin(int pin) const;

    public:
        void setup();
        void begin();
        void end();

        Value call(uint8_t opCode, Stack &stack, Heap &heap, Blob &bolb);
    };
};

#endif // __EONFUNC_H__
